version: "3"

services:
    wordpress:
        image: wordpress:latest
        ports:
            - "8080:80"
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress_password
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ./wordpress:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress_password
            MYSQL_RANDOM_ROOT_PASSWORD: "1"
        volumes:
            - mysql:/var/lib/mysql
        user: "999:999" # This ensures the container runs as the mysql user

volumes:
    wordpress:
    mysql:
